export const BASE_URL = "https://rickandmortyapi.com/api";

export const FETCH_CHARACTERS_START = "FETCH_CHARACTERS_START";
export const FETCH_CHARACTERS_SUCCESS = "FETCH_CHARACTERS_SUCCESS";
export const FETCH_CHARACTERS_RESPONSE = "FETCH_CHARACTERS_RESPONSE";
export const FETCH_CHARACTERS_FAILURE = "FETCH_CHARACTERS_FAILURE";

export const FETCH_CHARACTER_START = "FETCH_CHARACTER_START";
export const FETCH_CHARACTER_SUCCESS = "FETCH_CHARACTER_SUCCESS";
export const FETCH_CHARACTER_RESPONSE = "FETCH_CHARACTER_RESPONSE";
export const FETCH_CHARACTER_FAILURE = "FETCH_CHARACTER_FAILURE";

export const FETCH_EPISODE_START = "FETCH_EPISODE_START";
export const FETCH_EPISODE_SUCCESS = "FETCH_EPISODE_SUCCESS";
export const FETCH_EPISODE_RESPONSE = "FETCH_EPISODE_RESPONSE";
export const FETCH_EPISODE_FAILURE = "FETCH_EPISODE_FAILURE";

export const FETCH_EPISODES_START = "FETCH_EPISODES_START";
export const FETCH_EPISODES_SUCCESS = "FETCH_EPISODES_SUCCESS";
export const FETCH_EPISODES_RESPONSE = "FETCH_EPISODES_RESPONSE";
export const FETCH_EPISODES_FAILURE = "FETCH_EPISODES_FAILURE";

export const FETCH_LOCATIONS_START = "FETCH_LOCATIONS_START";
export const FETCH_LOCATIONS_SUCCESS = "FETCH_LOCATIONS_SUCCESS";
export const FETCH_LOCATIONS_RESPONSE = "FETCH_LOCATIONS_RESPONSE";
export const FETCH_LOCATIONS_FAILURE = "FETCH_LOCATIONS_FAILURE";

export const FETCH_LOCATION_START = "FETCH_LOCATION_START";
export const FETCH_LOCATION_SUCCESS = "FETCH_LOCATION_SUCCESS";
export const FETCH_LOCATION_RESPONSE = "FETCH_LOCATION_RESPONSE";
export const FETCH_LOCATION_FAILURE = "FETCH_LOCATION_FAILURE";
